--DROP TABLE TP_REFUND_FMBK_HST;
--DROP TABLE TP_REFUND_ACCOUNT_HST;
--DROP TABLE TP_REFUND_VRTL_ACT;
--DROP TABLE TP_REFUND_VRTL_ACT_HST;
--DROP TABLE TP_PAY_VRTL_ACT;
--DROP TABLE TP_PAY_VRTL_ACT_HST;
--DROP TABLE TP_PAY_VRTL_ACT_ERR_HST;
--DROP TABLE TP_VRTL_ACT_BAL;
--DROP TABLE TP_EXE_BDG_BAL;
--DROP TABLE TP_INDR_EXE_FMBK_HST;
--DROP TABLE TP_FMBK_HST;
--DROP TABLE TP_VRTL_ACT_TAX_INFO;
--DROP TABLE TP_TASK_ACT_BAL_MON;
--DROP TABLE TP_VRTL_ACT_INTEREST_UPLOAD_INFO;


CREATE TABLE TP_REFUND_FMBK_HST (
    ACT_N VARCHAR2(64),
    DPS VARCHAR2(100),
    TRNS_DT VARCHAR2(10),
    TRNS_TM VARCHAR2(6),
    OPT VARCHAR2(10),
    TRNS_AMT NUMBER(15),
    BAL_AMT NUMBER(15),
    RMK VARCHAR2(100),
    TASK_NO VARCHAR2(100),
    TASK_NM VARCHAR2(300),
    INST_NM VARCHAR2(100),
    MNR_NM VARCHAR2(300),
    MEMO VARCHAR2(100)
);

CREATE INDEX IDX_TP_REFUND_FMBK_HST_ACT_N ON TP_REFUND_FMBK_HST(ACT_N);
CREATE INDEX IDX_TP_REFUND_FMBK_HST_TASK_NO ON TP_REFUND_FMBK_HST(TASK_NO);

COMMENT ON TABLE TP_REFUND_FMBK_HST IS '환수내역조회';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.ACT_N IS '모계좌번호';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.DPS IS '계좌주';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.TRNS_DT IS '일자';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.TRNS_TM IS '시간';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.OPT IS '구분';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.TRNS_AMT IS '금액';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.BAL_AMT IS '잔액';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.RMK IS '적요';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.INST_NM IS '수행기관명';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.MNR_NM IS '책임자명';
COMMENT ON COLUMN TP_REFUND_FMBK_HST.MEMO IS '내용';

CREATE TABLE TP_REFUND_ACCOUNT_HST (
    BIZ_NM VARCHAR2(300),
    TASK_NO VARCHAR2(100),
    TASK_NM VARCHAR2(300),
    TASK_YR VARCHAR2(4),
    EXEC_TP VARCHAR2(6),
    ACT_N VARCHAR2(64),
    DPS VARCHAR2(100)
);

CREATE INDEX IDX_TP_REFUND_ACCOUNT_HST_BIZ_NM ON TP_REFUND_ACCOUNT_HST(BIZ_NM);
CREATE INDEX IDX_TP_REFUND_ACCOUNT_HST_TASK_NO ON TP_REFUND_ACCOUNT_HST(TASK_NO);
COMMENT ON TABLE TP_REFUND_ACCOUNT_HST IS '환수계좌등록현황조회';
COMMENT ON COLUMN TP_REFUND_ACCOUNT_HST.BIZ_NM IS '사업명';
COMMENT ON COLUMN TP_REFUND_ACCOUNT_HST.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_REFUND_ACCOUNT_HST.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_REFUND_ACCOUNT_HST.TASK_YR IS '협약년도';
COMMENT ON COLUMN TP_REFUND_ACCOUNT_HST.EXEC_TP IS '건별/일괄';
COMMENT ON COLUMN TP_REFUND_ACCOUNT_HST.ACT_N IS '계좌번호';
COMMENT ON COLUMN TP_REFUND_ACCOUNT_HST.DPS IS '예금주';

CREATE TABLE TP_REFUND_VRTL_ACT (
    TASK_NO VARCHAR2(100),
    TASK_TP VARCHAR2(12),
    BIZ_NM VARCHAR2(300),
    TASK_NM VARCHAR2(300),
    TASK_ST VARCHAR2(60),
    ACT_N VARCHAR2(64),
    VRTL_ACT_N VARCHAR2(64)
);

CREATE INDEX IDX_TP_REFUND_VRTL_ACT_TASK_NO ON TP_REFUND_VRTL_ACT(TASK_NO);
CREATE INDEX IDX_TP_REFUND_VRTL_ACT_VRTL_ACT_N ON TP_REFUND_VRTL_ACT(VRTL_ACT_N);

COMMENT ON TABLE TP_REFUND_VRTL_ACT IS '정산환수금 가상계좌번호 할당내역';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT.TASK_TP IS '과제분류';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT.BIZ_NM IS '사업명';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT.TASK_ST IS '과제상태';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT.ACT_N IS '모계좌번호';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT.VRTL_ACT_N IS '가상계좌번호';

CREATE TABLE TP_REFUND_VRTL_ACT_HST (
    TASK_NO VARCHAR2(100),
    BIZ_NM VARCHAR2(300),
    TASK_NM VARCHAR2(300),
    TRS_SEQ_N CHAR(7),
    TRS_DTM CHAR(14),
    ACT_N VARCHAR2(64),
    VRTL_ACT_N VARCHAR2(64),
    TRS_DPS VARCHAR2(100),
    TRS_AMT NUMBER(12)
);

CREATE INDEX IDX_TP_REFUND_VRTL_ACT_HST_TASK_NO ON TP_REFUND_VRTL_ACT_HST(TASK_NO);
CREATE INDEX IDX_TP_REFUND_VRTL_ACT_HST_VRTL_ACT_N ON TP_REFUND_VRTL_ACT_HST(VRTL_ACT_N);

COMMENT ON TABLE TP_REFUND_VRTL_ACT_HST IS '정산환수금 가상계좌 입금내역 조회';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT_HST.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT_HST.BIZ_NM IS '사업명';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT_HST.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT_HST.TRS_SEQ_N IS '거래번호';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT_HST.TRS_DTM IS '거래일시';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT_HST.ACT_N IS '입금 모계좌번호';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT_HST.VRTL_ACT_N IS '입금 가상계좌번호';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT_HST.TRS_DPS IS '출금인명';
COMMENT ON COLUMN TP_REFUND_VRTL_ACT_HST.TRS_AMT IS '입금액';

CREATE TABLE TP_PAY_VRTL_ACT (
    TASK_NO VARCHAR2(100),
    TASK_TP VARCHAR2(12),
    BIZ_NM VARCHAR2(300),
    TASK_NM VARCHAR2(300),
    TASK_ST VARCHAR2(60),
    ACT_N VARCHAR2(64),
    VRTL_ACT_N VARCHAR2(64)
);

CREATE INDEX IDX_TP_PAY_VRTL_ACT_TASK_NO ON TP_PAY_VRTL_ACT(TASK_NO);
CREATE INDEX IDX_TP_PAY_VRTL_ACT_VRTL_ACT_N ON TP_PAY_VRTL_ACT(VRTL_ACT_N);

COMMENT ON TABLE TP_PAY_VRTL_ACT IS '지급모계좌 가상계좌번호 할당내역';
COMMENT ON COLUMN TP_PAY_VRTL_ACT.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_PAY_VRTL_ACT.TASK_TP IS '과제분류';
COMMENT ON COLUMN TP_PAY_VRTL_ACT.BIZ_NM IS '사업명';
COMMENT ON COLUMN TP_PAY_VRTL_ACT.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_PAY_VRTL_ACT.TASK_ST IS '과제상태';
COMMENT ON COLUMN TP_PAY_VRTL_ACT.ACT_N IS '모계좌번호';
COMMENT ON COLUMN TP_PAY_VRTL_ACT.VRTL_ACT_N IS '가상계좌번호';

CREATE TABLE TP_PAY_VRTL_ACT_HST (
    TASK_NO VARCHAR2(100),
    BIZ_NM VARCHAR2(300),
    TASK_NM VARCHAR2(300),
    TRS_SEQ_N CHAR(7),
    TRS_DTM CHAR(14),
    ACT_N VARCHAR2(64),
    VRTL_ACT_N VARCHAR2(64),
    TRS_DPS VARCHAR2(100),
    TRS_AMT NUMBER(12)
);

CREATE INDEX IDX_TP_PAY_VRTL_ACT_HST_TASK_NO ON TP_PAY_VRTL_ACT_HST(TASK_NO);
CREATE INDEX IDX_TP_PAY_VRTL_ACT_HST_VRTL_ACT_N ON TP_PAY_VRTL_ACT_HST(VRTL_ACT_N);

COMMENT ON TABLE TP_PAY_VRTL_ACT_HST IS '지급모계좌 가상계좌 입금내역 조회';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_HST.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_HST.BIZ_NM IS '사업명';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_HST.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_HST.TRS_SEQ_N IS '거래번호';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_HST.TRS_DTM IS '거래일시';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_HST.ACT_N IS '입금 모계좌번호';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_HST.VRTL_ACT_N IS '입금 가상계좌번호';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_HST.TRS_DPS IS '출금인명';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_HST.TRS_AMT IS '입금액';

CREATE TABLE TP_PAY_VRTL_ACT_ERR_HST (
    VRTL_ACT_N VARCHAR2(64),
    ACT_N VARCHAR2(64),
    TRS_AMT NUMBER(12),
    TRS_DPS VARCHAR2(100),
    TRS_DTM CHAR(14)
);

CREATE INDEX IDX_TP_PAY_VRTL_ACT_ERR_HST_VRTL_ACT_N ON TP_PAY_VRTL_ACT_ERR_HST(VRTL_ACT_N);

COMMENT ON TABLE TP_PAY_VRTL_ACT_ERR_HST IS '민간부담금 오입금처리';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_ERR_HST.VRTL_ACT_N IS '가상계좌번호';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_ERR_HST.ACT_N IS '모계좌번호';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_ERR_HST.TRS_AMT IS '금액';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_ERR_HST.TRS_DPS IS '입금인성명';
COMMENT ON COLUMN TP_PAY_VRTL_ACT_ERR_HST.TRS_DTM IS '이체일시';


CREATE TABLE TP_VRTL_ACT_BAL (
    TASK_NO VARCHAR2(100),
    TASK_NM VARCHAR2(300),
    INST_NM VARCHAR2(100),
    MNR_NM VARCHAR2(300),
    TASK_ST VARCHAR2(60),
    CURYR_STARTDT VARCHAR2(10),
    CURYR_ENDDT VARCHAR2(10),
    ACT_N VARCHAR2(64),
    PAY_VRTL_ACT_N VARCHAR2(64),
    REFUND_VRTL_ACT_N VARCHAR2(64),
    BAL_AMT NUMBER(15),
    BAL_ST_DTM VARCHAR2(18),
    TRS_AMT NUMBER(22),
    INTEREST_SUM_AMT NUMBER(12),
    IN_INTEREST NUMBER(12)
);

CREATE INDEX IDX_TP_VRTL_ACT_BAL_TASK_NO ON TP_VRTL_ACT_BAL(TASK_NO);

COMMENT ON TABLE TP_VRTL_ACT_BAL IS '지급가상계좌 이체';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.INST_NM IS '연구기관';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.MNR_NM IS '책임자';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.TASK_ST IS '과제상태';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.CURYR_STARTDT IS '당해년도 수행기간 시작';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.CURYR_ENDDT IS '당해년도 수행기간 끝';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.ACT_N IS '모계좌번호';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.PAY_VRTL_ACT_N IS '지급가상계좌';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.REFUND_VRTL_ACT_N IS '정산환수금반납계좌';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.BAL_AMT IS '가상계좌잔액';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.BAL_ST_DTM IS '가상계좌잔액조회시간';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.TRS_AMT IS '이체금액';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.INTEREST_SUM_AMT IS '합산이자';
COMMENT ON COLUMN TP_VRTL_ACT_BAL.IN_INTEREST IS '기간내이자';

CREATE TABLE TP_EXE_BDG_BAL (
    TASK_NO VARCHAR2(100),
    TASK_NM VARCHAR2(300),
    TASK_ST VARCHAR2(60),
    MNR_NM VARCHAR2(300),
    CURYR_STARTDT VARCHAR2(10),
    CURYR_ENDDT VARCHAR2(10),
    BDG_CS_AMT NUMBER(15),
    EXE_CS_BAL NUMBER(15),
    ACT_BAL NUMBER(15),
    ALERT_CNT NUMBER(12),
    ALERT_DT VARCHAR2(10),
    EXEC_TP VARCHAR2(6)
);

CREATE INDEX IDX_TP_EXE_BDG_BAL_TASK_NO ON TP_EXE_BDG_BAL(TASK_NO);

COMMENT ON TABLE TP_EXE_BDG_BAL IS '연구비 잔액현황';
COMMENT ON COLUMN TP_EXE_BDG_BAL.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_EXE_BDG_BAL.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_EXE_BDG_BAL.TASK_ST IS '과제상태';
COMMENT ON COLUMN TP_EXE_BDG_BAL.MNR_NM IS '책임자명';
COMMENT ON COLUMN TP_EXE_BDG_BAL.CURYR_STARTDT IS '당해년도 수행기간 시작';
COMMENT ON COLUMN TP_EXE_BDG_BAL.CURYR_ENDDT IS '당해년도 수행기간 끝';
COMMENT ON COLUMN TP_EXE_BDG_BAL.BDG_CS_AMT IS '총연구비예산';
COMMENT ON COLUMN TP_EXE_BDG_BAL.EXE_CS_BAL IS '연구비입력기준집행잔액';
COMMENT ON COLUMN TP_EXE_BDG_BAL.ACT_BAL IS '연구비전용계좌집행잔액';
COMMENT ON COLUMN TP_EXE_BDG_BAL.ALERT_CNT IS '고액금액이체발생누적건수';
COMMENT ON COLUMN TP_EXE_BDG_BAL.ALERT_DT IS '최근고액금액이체발생일자';
COMMENT ON COLUMN TP_EXE_BDG_BAL.EXEC_TP IS '건별/일괄';

CREATE TABLE TP_INDR_EXE_FMBK_HST (
    TASK_NO VARCHAR2(100),
    TASK_NM VARCHAR2(300),
    TRS_SEQ_N1 CHAR(8),
    VRTL_ACT_N VARCHAR2(64),
    TRS_AMT1 NUMBER(15),
    ETP_ACT_N VARCHAR2(64),
    EXE_ACT_N VARCHAR2(64),
    RG_ID VARCHAR2(20),
    TRS_RCD1 CHAR(4),
    TRS_RCD_MSG1 VARCHAR2(1500),
    TRS_DTM1 CHAR(14),
    TRS_SEQ_N2 CHAR(8),
    RSE_ACT_N VARCHAR2(64),
    TRS_AMT2 NUMBER(15),
    TRS_ACT_N VARCHAR2(64),
    BNK_NM VARCHAR2(30),
    DPS_NM VARCHAR2(100),
    TRS_RCD2 CHAR(4),
    TRS_RCD_MSG2 VARCHAR2(1500),
    TRS_DTM2 CHAR(14)
);

CREATE INDEX IDX_TP_INDR_EXE_FMBK_HST_TASK_NO ON TP_INDR_EXE_FMBK_HST(TASK_NO);

COMMENT ON TABLE TP_INDR_EXE_FMBK_HST IS '3자이체 거래내역';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_SEQ_N1 IS '거래번호1';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.VRTL_ACT_N IS '가상계좌';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_AMT1 IS '지급금액1';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.ETP_ACT_N IS '경유계좌';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.EXE_ACT_N IS '모계좌';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.RG_ID IS '등록id';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_RCD1 IS '처리코드1';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_RCD_MSG1 IS '처리메세지1';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_DTM1 IS '처리일시1';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_SEQ_N2 IS '거래번호2';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.RSE_ACT_N IS '연구비계좌';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_AMT2 IS '지급금액2';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_ACT_N IS '거래처계좌';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.BNK_NM IS '은행명';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.DPS_NM IS '예금주';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_RCD2 IS '처리코드2';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_RCD_MSG2 IS '처리메세지2';
COMMENT ON COLUMN TP_INDR_EXE_FMBK_HST.TRS_DTM2 IS '처리일시2';

CREATE TABLE TP_FMBK_HST (
    TRS_N CHAR(8),
    TRS_DT CHAR(8),
    TRS_KND VARCHAR2(50),
    TRS_RCD CHAR(4),
    RCD_MSG VARCHAR2(1500),
    TASK_NO VARCHAR2(100),
    TASK_NM VARCHAR2(300),
    TRS_AMT NUMBER(15),
    REQ_MSG VARCHAR2(1500)
);

CREATE INDEX IDX_TP_FMBK_HST_TRS_N ON TP_FMBK_HST(TRS_N);
CREATE INDEX IDX_TP_FMBK_HST_TRS_DT ON TP_FMBK_HST(TRS_DT);
CREATE INDEX IDX_TP_FMBK_HST_TRS_KND ON TP_FMBK_HST(TRS_KND);
CREATE INDEX IDX_TP_FMBK_HST_TASK_NO ON TP_FMBK_HST(TASK_NO);

COMMENT ON TABLE TP_FMBK_HST IS '펌뱅킹 거래내역';
COMMENT ON COLUMN TP_FMBK_HST.TRS_N IS '거래번호';
COMMENT ON COLUMN TP_FMBK_HST.TRS_DT IS '거래일시';
COMMENT ON COLUMN TP_FMBK_HST.TRS_KND IS '거래구분';
COMMENT ON COLUMN TP_FMBK_HST.TRS_RCD IS '결과코드';
COMMENT ON COLUMN TP_FMBK_HST.RCD_MSG IS '결과메세지';
COMMENT ON COLUMN TP_FMBK_HST.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_FMBK_HST.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_FMBK_HST.TRS_AMT IS '이체금액';
COMMENT ON COLUMN TP_FMBK_HST.REQ_MSG IS '요청메세지';

CREATE TABLE TP_VRTL_ACT_TAX_INFO (
    BIZ_NM VARCHAR2(300),
    TASK_TP VARCHAR2(12),
    TASK_NO VARCHAR2(100),
    TASK_NM VARCHAR2(300),
    TASK_ST VARCHAR2(60),
    ACT_N VARCHAR2(64),
    VRTL_ACT_N VARCHAR2(64),
    TAX_TP VARCHAR2(100)
);

CREATE INDEX IDX_TP_VRTL_ACT_TAX_INFO_BIZ_NM ON TP_VRTL_ACT_TAX_INFO(BIZ_NM);
CREATE INDEX IDX_TP_VRTL_ACT_TAX_INFO_TASK_NO ON TP_VRTL_ACT_TAX_INFO(TASK_NO);

COMMENT ON TABLE TP_VRTL_ACT_TAX_INFO IS '지급가상계좌 과세등록';
COMMENT ON COLUMN TP_VRTL_ACT_TAX_INFO.BIZ_NM IS '사업명';
COMMENT ON COLUMN TP_VRTL_ACT_TAX_INFO.TASK_TP IS '과제분류';
COMMENT ON COLUMN TP_VRTL_ACT_TAX_INFO.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_VRTL_ACT_TAX_INFO.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_VRTL_ACT_TAX_INFO.TASK_ST IS '과제상태';
COMMENT ON COLUMN TP_VRTL_ACT_TAX_INFO.ACT_N IS '모계좌번호';
COMMENT ON COLUMN TP_VRTL_ACT_TAX_INFO.VRTL_ACT_N IS '가상계좌번호';
COMMENT ON COLUMN TP_VRTL_ACT_TAX_INFO.TAX_TP IS '과세유형';

CREATE TABLE TP_TASK_ACT_BAL_MON (
    TRS_DT CHAR(8),
    TASK_NO VARCHAR2(100),
    VRTL_ACT_N VARCHAR2(64),
    VRTL_ACT_BAL_A NUMBER(15),
    CASH_BDG_BAL_B NUMBER(15),
    INTEREST_C NUMBER(15),
    REG_INTEREST_D NUMBER(15),
    PRE_PAY_AMT_F NUMBER(15),
    TOT_CASH_BDG NUMBER(15),
    GOV_CS NUMBER(15),
    CVN_CS NUMBER(15),
    INTEREST_BDG NUMBER(15),
    TASK_NM VARCHAR2(300),
    INST_NM VARCHAR2(100),
    MNR_NM VARCHAR2(300),
    TASK_ST VARCHAR2(60)
);

CREATE INDEX IDX_TP_TASK_ACT_BAL_MON_TRS_DT ON TP_TASK_ACT_BAL_MON(TRS_DT);
CREATE INDEX IDX_TP_TASK_ACT_BAL_MON_TASK_NO ON TP_TASK_ACT_BAL_MON(TASK_NO);

COMMENT ON TABLE TP_TASK_ACT_BAL_MON IS '가상계좌잔액 모니터링';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.TRS_DT IS '일자';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.VRTL_ACT_N IS '가상계좌번호';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.VRTL_ACT_BAL_A IS '가상계좌잔액_A';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.CASH_BDG_BAL_B IS '현금예산잔액_B';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.INTEREST_C IS '이자_C';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.REG_INTEREST_D IS '등록이자_D';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.PRE_PAY_AMT_F IS '카드선입금 미등록금액_F';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.TOT_CASH_BDG IS '현금총예산';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.GOV_CS IS '정부출연금';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.CVN_CS IS '민간부담금';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.INTEREST_BDG IS '이자예산';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.TASK_NM IS '과제명';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.INST_NM IS '기관명';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.MNR_NM IS '책임자명';
COMMENT ON COLUMN TP_TASK_ACT_BAL_MON.TASK_ST IS '과제상태';

CREATE TABLE TP_VRTL_ACT_INTEREST_UPLOAD_INFO (
    TRS_DTM CHAR(14),
    HNDL_ORG_CD CHAR(8),
    TRS_SND_DTM CHAR(14),
    OPN_ORG_CD CHAR(8),
    RCP_ACT_N VARCHAR2(64),
    RCP_ACT_NM VARCHAR2(64),
    TRS_AMT NUMBER(12),
    INPT_DTM CHAR(14)
);

CREATE INDEX IDX_TP_VRTL_ACT_INTEREST_UPLOAD_INFO_TRS_DTM ON TP_VRTL_ACT_INTEREST_UPLOAD_INFO(TRS_DTM);

COMMENT ON TABLE TP_VRTL_ACT_INTEREST_UPLOAD_INFO IS '가상계좌이자 업로드';
COMMENT ON COLUMN TP_VRTL_ACT_INTEREST_UPLOAD_INFO.TRS_DTM IS '거래일시';
COMMENT ON COLUMN TP_VRTL_ACT_INTEREST_UPLOAD_INFO.HNDL_ORG_CD IS '송수신기관코드';
COMMENT ON COLUMN TP_VRTL_ACT_INTEREST_UPLOAD_INFO.TRS_SND_DTM IS '전송일시';
COMMENT ON COLUMN TP_VRTL_ACT_INTEREST_UPLOAD_INFO.OPN_ORG_CD IS '개설기관코드';
COMMENT ON COLUMN TP_VRTL_ACT_INTEREST_UPLOAD_INFO.RCP_ACT_N IS '입금계좌번호';
COMMENT ON COLUMN TP_VRTL_ACT_INTEREST_UPLOAD_INFO.RCP_ACT_NM IS '입금계좌성명';
COMMENT ON COLUMN TP_VRTL_ACT_INTEREST_UPLOAD_INFO.TRS_AMT IS '이자';
COMMENT ON COLUMN TP_VRTL_ACT_INTEREST_UPLOAD_INFO.INPT_DTM IS '입력일시';
