-- DROP TABLE TP_ACT;
-- DROP TABLE TP_BDG;
-- DROP TABLE TP_BIZ;
-- DROP TABLE TP_BSN_C;
-- DROP TABLE TP_EXEC;
-- DROP TABLE TP_EXEC_FILE;
-- DROP TABLE TP_EXEC_GB;
-- DROP TABLE TP_EXEC_TAX_INVOICE;
-- DROP TABLE TP_FND_BDG;
-- DROP TABLE TP_IOE;
-- DROP TABLE TP_IOE_CD;
-- DROP TABLE TP_IOE_GRP;
-- DROP TABLE TP_IOE_GRP_CD;
-- DROP TABLE TP_PART;
-- DROP TABLE TP_STL_DOC;
-- DROP TABLE TP_TASK;
-- DROP TABLE TP_TASK_IOE_GRP;
-- DROP TABLE TP_TAX_INV;
-- DROP TABLE TP_TAX_INV_ITM;


-- TP_ACT definition
CREATE TABLE "TP_ACT"
   (	"SEQ_N" NUMBER(15,0) NOT NULL ENABLE,
	"TASK_NO" VARCHAR2(100) NOT NULL ENABLE,
	"ACT_TP" VARCHAR2(2) NOT NULL ENABLE,
	"BNK_NM" VARCHAR2(100),
	"ACT_NO" VARCHAR2(100),
	"ACT_NM" VARCHAR2(100),
	 CONSTRAINT "PK_TP_ACT" PRIMARY KEY ("SEQ_N")
   );

CREATE INDEX IDX_TP_ACT_1 ON TP_ACT (TASK_NO);

COMMENT ON COLUMN TP_ACT.SEQ_N IS '순번';
COMMENT ON COLUMN TP_ACT.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_ACT.ACT_TP IS '계좌종류';
COMMENT ON COLUMN TP_ACT.BNK_NM IS '은행명';
COMMENT ON COLUMN TP_ACT.ACT_NO IS '계좌번호';
COMMENT ON COLUMN TP_ACT.ACT_NM IS '예금주명';

-- TP_BDG definition
CREATE TABLE "TP_BDG"
   (	"TASK_NO" VARCHAR2(100) NOT NULL ENABLE,
	"CNV_NMT" VARCHAR2(2) NOT NULL ENABLE,
	"BDG_KND_CD" VARCHAR2(2) NOT NULL ENABLE,
	"IOE_GRP_CD" VARCHAR2(3) NOT NULL ENABLE,
	"IOE_CD" VARCHAR2(8) NOT NULL ENABLE,
	"CS_AMT" NUMBER(15,0),
	"TH_AMT" NUMBER(15,0),
	"RMK" VARCHAR2(200),
	 CONSTRAINT "PK_TP_BDG" PRIMARY KEY ("TASK_NO", "CNV_NMT", "BDG_KND_CD", "IOE_GRP_CD", "IOE_CD")
   );

CREATE INDEX IDX_TP_BDG_1 ON TP_BDG (TASK_NO);

COMMENT ON COLUMN TP_BDG.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_BDG.CNV_NMT IS '협약 차수';
COMMENT ON COLUMN TP_BDG.BDG_KND_CD IS '예산 종류 코드 (최초, 최종, 이월금, 이자)';
COMMENT ON COLUMN TP_BDG.IOE_GRP_CD IS '비목 그룹 코드';
COMMENT ON COLUMN TP_BDG.IOE_CD IS '비목 코드';
COMMENT ON COLUMN TP_BDG.CS_AMT IS '현금액';
COMMENT ON COLUMN TP_BDG.TH_AMT IS '현물액';
COMMENT ON COLUMN TP_BDG.RMK IS '비고';

-- TP_BIZ
CREATE TABLE "TP_BIZ"
   (	"BIZ_CD" VARCHAR2(100) NOT NULL ENABLE,
	"BIZ_NM" VARCHAR2(300),
	"PRT_CD" VARCHAR2(100),
	 CONSTRAINT "PK_TP_BIZ" PRIMARY KEY ("BIZ_CD")
	 );

COMMENT ON COLUMN TP_BIZ.BIZ_CD IS '사업코드';
COMMENT ON COLUMN TP_BIZ.BIZ_NM IS '사업명';
COMMENT ON COLUMN TP_BIZ.PRT_CD IS '부모코드';

-- TP_BSN_C definition
CREATE TABLE "TP_BSN_C"
   (	"BSN_C_CD" VARCHAR2(20) NOT NULL ENABLE,
	"BSN_NM" VARCHAR2(300),
	"UP_BSN_CD" VARCHAR2(20),
	 CONSTRAINT "PK_TP_BSN_C" PRIMARY KEY ("BSN_C_CD")
	 );

COMMENT ON COLUMN TP_BSN_C.BSN_C_CD IS '사업코드';
COMMENT ON COLUMN TP_BSN_C.BSN_NM IS '사업명';
COMMENT ON COLUMN TP_BSN_C.UP_BSN_CD IS '부모코드';

-- TP_EXEC definition
CREATE TABLE "TP_EXEC"
   (	"TASK_NO" VARCHAR2(100),
	"EXEC_NO" VARCHAR2(100) NOT NULL ENABLE,
	"EXEC_DT" VARCHAR2(14),
	"EXEC_MTD" VARCHAR2(2),
	"IOE_CD" VARCHAR2(100),
	"RMK" VARCHAR2(4000),
	"EXEC_AMT" NUMBER(15,0),
	"VAT" NUMBER(15,0),
	"STS" VARCHAR2(3),
	"USG" VARCHAR2(200),
	"APPR_NO" VARCHAR2(100),
	"MCT" VARCHAR2(100),
	"RG_DT" VARCHAR2(8),
	"MD_DT" VARCHAR2(8),
	"RG_MTD" VARCHAR2(2),
	"TRNS_TYPE" VARCHAR2(3),
	"TRNS_DT" VARCHAR2(8),
	"TRNS_AMT" NUMBER(15,0),
	"TRNS_RST" VARCHAR2(150),
	"IOE_GRP_CD" VARCHAR2(3),
	"CE_EXE_SEQ_N" VARCHAR2(17),
	"R_EXE_SEQ_N" VARCHAR2(17),
	"TIB_C" VARCHAR2(2),
	"MATCH_ID" VARCHAR2(100),
	 CONSTRAINT "PK_TP_EXEC" PRIMARY KEY ("EXEC_NO")
	 );

CREATE INDEX IDX_TP_EXEC_1 ON TP_EXEC (TASK_NO);
CREATE INDEX IDX_TP_EXEC_2 ON TP_EXEC (TASK_NO, R_EXE_SEQ_N, EXEC_NO);

COMMENT ON COLUMN TP_EXEC.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_EXEC.EXEC_NO IS '집행번호';
COMMENT ON COLUMN TP_EXEC.EXEC_DT IS '집행일자';
COMMENT ON COLUMN TP_EXEC.EXEC_MTD IS '집행방법';
COMMENT ON COLUMN TP_EXEC.IOE_CD IS '비목';
COMMENT ON COLUMN TP_EXEC.RMK IS '세부내역';
COMMENT ON COLUMN TP_EXEC.EXEC_AMT IS '집행금액';
COMMENT ON COLUMN TP_EXEC.VAT IS '부가세';
COMMENT ON COLUMN TP_EXEC.STS IS '상태';
COMMENT ON COLUMN TP_EXEC.USG IS '사용처';
COMMENT ON COLUMN TP_EXEC.APPR_NO IS '승인번호';
COMMENT ON COLUMN TP_EXEC.MCT IS '가맹점';
COMMENT ON COLUMN TP_EXEC.RG_DT IS '등록일자';
COMMENT ON COLUMN TP_EXEC.MD_DT IS '수정일자';
COMMENT ON COLUMN TP_EXEC.RG_MTD IS '등록방법';
COMMENT ON COLUMN TP_EXEC.TRNS_TYPE IS '이체처리구분';
COMMENT ON COLUMN TP_EXEC.TRNS_DT IS '이체일자';
COMMENT ON COLUMN TP_EXEC.TRNS_AMT IS '지급금액';
COMMENT ON COLUMN TP_EXEC.TRNS_RST IS '이체처리결과';
COMMENT ON COLUMN TP_EXEC.IOE_GRP_CD IS '비목그룹코드';
COMMENT ON COLUMN TP_EXEC.CE_EXE_SEQ_N IS '취소집행번호';
COMMENT ON COLUMN TP_EXEC.R_EXE_SEQ_N IS '원집행번호';
COMMENT ON COLUMN TP_EXEC.TIB_C IS '취소코드';
COMMENT ON COLUMN TP_EXEC.MATCH_ID IS '집행고유번호';

IOE_GRP_CD
CE_EXE_SEQ_N
R_EXE_SEQ_N
TIB_C
MATCH_ID
-- TP_EXEC_FILE definition
CREATE TABLE "TP_EXEC_FILE"
   (	"TASK_NO" VARCHAR2(100) NOT NULL ENABLE,
	"EXEC_NO" VARCHAR2(100) NOT NULL ENABLE,
	"SEQ_N" NUMBER(3,0) NOT NULL ENABLE,
	"FILE_PATH" VARCHAR2(100),
	"FILE_NM" VARCHAR2(2000),
	"FILE_ORG_NM" VARCHAR2(2000),
	 CONSTRAINT "PK_TP_EXEC_FILE" PRIMARY KEY ("TASK_NO", "EXEC_NO", "SEQ_N")
	 );

CREATE INDEX IDX_TP_EXEC_FILE_1 ON TP_EXEC_FILE (TASK_NO);

COMMENT ON COLUMN TP_EXEC_FILE.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_EXEC_FILE.EXEC_NO IS '집행번호';
COMMENT ON COLUMN TP_EXEC_FILE.SEQ_N IS '순번';
COMMENT ON COLUMN TP_EXEC_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TP_EXEC_FILE.FILE_NM IS '파일명';
COMMENT ON COLUMN TP_EXEC_FILE.FILE_ORG_NM IS '파일기관명';


-- TP_EXEC_GB definition
CREATE TABLE "TP_EXEC_GB"
   (	"TASK_NO" VARCHAR2(100) NOT NULL ENABLE,
	"GB_CD" VARCHAR2(2),
	"TYPE_CD" VARCHAR2(2) NOT NULL ENABLE,
	"CNT" NUMBER(13,0),
	"AMT" NUMBER(13,0),
	"TAX" NUMBER(13,0),
	"REG_AMT" NUMBER(13,0),
	"RAT" NUMBER(5,0),
	 CONSTRAINT "PK_TP_EXEC_GB" PRIMARY KEY ("TASK_NO", "TYPE_CD")
	 );
CREATE INDEX IDX_TP_EXEC_GB ON TP_EXEC_GB (TASK_NO);

COMMENT ON COLUMN TP_EXEC_GB.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_EXEC_GB.GB_CD IS '구분 (1: 카드사용내역, 2: 계좌이체/기타내역)';
COMMENT ON COLUMN TP_EXEC_GB.TYPE_CD IS '종류 (연구비 카드, 계좌이체 등)';
COMMENT ON COLUMN TP_EXEC_GB.CNT IS '건수';
COMMENT ON COLUMN TP_EXEC_GB.AMT IS '금액';
COMMENT ON COLUMN TP_EXEC_GB.TAX IS '부가세';
COMMENT ON COLUMN TP_EXEC_GB.REG_AMT IS '등록된 집행액';
COMMENT ON COLUMN TP_EXEC_GB.RAT IS '집행비율';

-- TP_EXEC_TAX_INVOICE definition
CREATE TABLE "TP_EXEC_TAX_INVOICE"
   (	"EXEC_NO" VARCHAR2(100) NOT NULL ENABLE,
	"ISSUE_ID" VARCHAR2(24) NOT NULL ENABLE,
	 CONSTRAINT "PK_TP_EXEC_TAX_INVOICE" PRIMARY KEY ("EXEC_NO", "ISSUE_ID")
	 );

COMMENT ON COLUMN TP_EXEC_TAX_INVOICE.EXEC_NO IS '집행번호';
COMMENT ON COLUMN TP_EXEC_TAX_INVOICE.ISSUE_ID IS '세금계산서 승인번호';

-- TP_FND_BDG definition
CREATE TABLE "TP_FND_BDG"
   (	"TASK_NO" VARCHAR2(100) NOT NULL ENABLE,
	"FND_TP" VARCHAR2(2) NOT NULL ENABLE,
	"CASH" NUMBER(15,0),
	"NON_CASH" NUMBER(15,0),
	"TOT" NUMBER(15,0),
	 CONSTRAINT "PK_TP_FND_BDG" PRIMARY KEY ("TASK_NO", "FND_TP")
	 );

-- TP_IOE definition
CREATE TABLE "TP_IOE"
   (	"IOE_CD" VARCHAR2(100) NOT NULL ENABLE,
	"IOE_NM" VARCHAR2(300),
	"PRT_CD" VARCHAR2(100),
	 CONSTRAINT "PK_TP_IOE" PRIMARY KEY ("IOE_CD")
	 );

COMMENT ON COLUMN TP_IOE.IOE_CD IS '비목코드';
COMMENT ON COLUMN TP_IOE.IOE_NM IS '비목명';
COMMENT ON COLUMN TP_IOE.PRT_CD IS '부모코드';

-- TP_IOE_CD definition
CREATE TABLE "TP_IOE_CD"
   (	"IOE_CD" VARCHAR2(8) NOT NULL ENABLE,
	"IOE_C" VARCHAR2(1),
	"ESST_INPT_F" VARCHAR2(1),
	"SUM_INPT_F" VARCHAR2(1),
	"FOUR_LRG_IOE_C" VARCHAR2(2),
	"RMK_USE_F" VARCHAR2(1),
	"USE_F" VARCHAR2(1),
	"EXE_ABLE_AMT_COND" VARCHAR2(10),
	"UP_IOE_CD" VARCHAR2(8),
	"MNST_IOE_CD" VARCHAR2(20),
	"FEE_IOE_F" VARCHAR2(1),
	"OV_INPT_F" VARCHAR2(1),
	"DTL_C_CD" VARCHAR2(2),
	"ECL_DOC_N" VARCHAR2(1),
	"IOE_CS_CD" VARCHAR2(1),
	"WT_IOE_C" VARCHAR2(1),
	 CONSTRAINT "PK_TP_IOE_CD" PRIMARY KEY ("IOE_CD")
	 );

COMMENT ON COLUMN TP_IOE_CD.IOE_CD IS '비목 코드';
COMMENT ON COLUMN TP_IOE_CD.IOE_C IS '비목 분류';
COMMENT ON COLUMN TP_IOE_CD.ESST_INPT_F IS '필수 입력 여부';
COMMENT ON COLUMN TP_IOE_CD.SUM_INPT_F IS '합계 영향 여부';
COMMENT ON COLUMN TP_IOE_CD.FOUR_LRG_IOE_C IS '4대비목';
COMMENT ON COLUMN TP_IOE_CD.RMK_USE_F IS '적용 사용 여부';
COMMENT ON COLUMN TP_IOE_CD.USE_F IS '사용 여부';
COMMENT ON COLUMN TP_IOE_CD.EXE_ABLE_AMT_COND IS '집행 가능 금액';
COMMENT ON COLUMN TP_IOE_CD.UP_IOE_CD IS '상위 비목 코드';
COMMENT ON COLUMN TP_IOE_CD.MNST_IOE_CD IS '부처 비목 코드';
COMMENT ON COLUMN TP_IOE_CD.FEE_IOE_F IS '수수료 비목 여부';
COMMENT ON COLUMN TP_IOE_CD.OV_INPT_F IS '초과 입력 여부';
COMMENT ON COLUMN TP_IOE_CD.DTL_C_CD IS '세목 구분 코드';
COMMENT ON COLUMN TP_IOE_CD.ECL_DOC_N IS '정산 증빙 구분';
COMMENT ON COLUMN TP_IOE_CD.IOE_CS_CD IS '현금,현물 관리 구분';
COMMENT ON COLUMN TP_IOE_CD.WT_IOE_C IS '위탁개발비 비세목 여부';

-- TP_IOE_GRP definition
CREATE TABLE "TP_IOE_GRP"
   (	"IOE_GRP_CD" VARCHAR2(3) NOT NULL ENABLE,
	"IOE_GRP_NM" VARCHAR2(300),
	 CONSTRAINT "PK_TP_IOE_GRP" PRIMARY KEY ("IOE_GRP_CD")
	 );

COMMENT ON COLUMN TP_IOE_GRP.IOE_GRP_CD IS '비목 그룹 코드';
COMMENT ON COLUMN TP_IOE_GRP.IOE_GRP_NM IS '비목 그룹 명';

-- TP_IOE_GRP_CD definition
CREATE TABLE "TP_IOE_GRP_CD"
   (	"IOE_GRP_CD" VARCHAR2(3) NOT NULL ENABLE,
	"IOE_CD" VARCHAR2(8) NOT NULL ENABLE,
	"NM" VARCHAR2(300),
	"LUP_N" VARCHAR2(3),
	"NM_ABRV" VARCHAR2(100),
	"RMK" VARCHAR2(4000),
	 CONSTRAINT "PK_TP_IOE_GRP_CD" PRIMARY KEY ("IOE_GRP_CD", "IOE_CD")
	 );

COMMENT ON COLUMN TP_IOE_GRP_CD.IOE_GRP_CD IS '비목 그룹 코드';
COMMENT ON COLUMN TP_IOE_GRP_CD.IOE_CD IS '비목 코드';
COMMENT ON COLUMN TP_IOE_GRP_CD.NM IS '이름';
COMMENT ON COLUMN TP_IOE_GRP_CD.LUP_N IS '정렬';
COMMENT ON COLUMN TP_IOE_GRP_CD.NM_ABRV IS '약어';
COMMENT ON COLUMN TP_IOE_GRP_CD.RMK IS '설명';

-- TP_PART definition
CREATE TABLE "TP_PART"
   (
   "SEQ_N" NUMBER(15,0) NOT NULL ENABLE,
	"TASK_NO" VARCHAR2(100) NOT NULL ENABLE,
	"NM" VARCHAR2(300),
	"ENG_NM" VARCHAR2(100),
	"GD" VARCHAR2(100),
	"IS_MNG" VARCHAR2(100),
	"DOB" VARCHAR2(100),
	"EMAIL" VARCHAR2(100),
	"PHONE" VARCHAR2(100),
	"PART_STARTDT" VARCHAR2(8),
	"PART_ENDDT" VARCHAR2(8),
	"PART_RAT" NUMBER(5,2),
	"ORG" VARCHAR2(300),
	"DEPT" VARCHAR2(300),
	"POS" VARCHAR2(300),
	"IS_PART" VARCHAR2(1),
	CONSTRAINT "PK_TP_PART" PRIMARY KEY ("SEQ_N")
   );

CREATE INDEX IDX_TP_PART ON TP_PART (TASK_NO);

COMMENT ON COLUMN TP_PART.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_PART.NM IS '이름';
COMMENT ON COLUMN TP_PART.ENG_NM IS '영문이름';
COMMENT ON COLUMN TP_PART.GD IS '성별';
COMMENT ON COLUMN TP_PART.IS_MNG IS '책임자여부';
COMMENT ON COLUMN TP_PART.DOB IS '생년월일';
COMMENT ON COLUMN TP_PART.EMAIL IS '이메일';
COMMENT ON COLUMN TP_PART.PHONE IS '휴대폰';
COMMENT ON COLUMN TP_PART.PART_STARTDT IS '참여기간시작';
COMMENT ON COLUMN TP_PART.PART_ENDDT IS '참여기간종료';
COMMENT ON COLUMN TP_PART.PART_RAT IS '참여율';
COMMENT ON COLUMN TP_PART.ORG IS '소속기관';
COMMENT ON COLUMN TP_PART.DEPT IS '소속부서';
COMMENT ON COLUMN TP_PART.POS IS '직위';

-- TP_STL_DOC definition
CREATE TABLE "TP_STL_DOC"
   (	"TASK_NO" VARCHAR2(100) NOT NULL ENABLE,
	"RTM_ITM" VARCHAR2(10) NOT NULL ENABLE,
	"RTM_KEY" VARCHAR2(200) NOT NULL ENABLE,
	"SEQ_N" NUMBER(3,0) NOT NULL ENABLE,
	"FILE_PATH" VARCHAR2(100),
	"FILE_NM" VARCHAR2(2000),
	"FILE_ORG_NM" VARCHAR2(2000),
	 CONSTRAINT "PK_TP_STL_DOC" PRIMARY KEY ("TASK_NO", "RTM_ITM", "RTM_KEY", "SEQ_N")
	 );

CREATE INDEX IDX_TP_STL_DOC ON TP_STL_DOC (TASK_NO);

COMMENT ON COLUMN TP_STL_DOC.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_STL_DOC.RTM_ITM IS '체크항목';
COMMENT ON COLUMN TP_STL_DOC.RTM_KEY IS '거래키';
COMMENT ON COLUMN TP_STL_DOC.SEQ_N IS '순번';
COMMENT ON COLUMN TP_STL_DOC.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TP_STL_DOC.FILE_NM IS '파일명';
COMMENT ON COLUMN TP_STL_DOC.FILE_ORG_NM IS '파일기관명';

-- TP_TASK definition
CREATE TABLE "TP_TASK"
   (	"TASK_NO" VARCHAR2(100) NOT NULL ENABLE,
	"TASK_NM" VARCHAR2(300),
	"TASK_YR" VARCHAR2(4),
	"TASK_TP" VARCHAR2(2),
	"TASK_ST" VARCHAR2(3),
	"MNR_NM" VARCHAR2(300),
	"MNR_BIRTHDT" VARCHAR2(100),
	"MNR_ENGNM" VARCHAR2(100),
	"MNR_EMAIL" VARCHAR2(100),
	"MNR_POS" VARCHAR2(100),
	"MNR_DEPT" VARCHAR2(100),
	"MNR_PHONE" VARCHAR2(100),
	"MNR_FAX" VARCHAR2(100),
	"INST_NM" VARCHAR2(100),
	"INST_BIZNO" VARCHAR2(20),
	"CURYR_STARTDT" VARCHAR2(8),
	"CURYR_ENDDT" VARCHAR2(8),
	"TOTAL_STARTDT" VARCHAR2(8),
	"TOTAL_ENDDT" VARCHAR2(8),
	"SUB_FD" VARCHAR2(100),
	"STL_AGC" VARCHAR2(100),
	"EXEC_TP" VARCHAR2(2),
	"BIZ_CD" VARCHAR2(100),
	"STL_PHONE" VARCHAR2(100),
	"STL_EMAIL" VARCHAR2(100),
	"MNR_GD" VARCHAR2(2),
	 CONSTRAINT "PK_TP_TASK" PRIMARY KEY ("TASK_NO")
	 );

-- TP_TASK_IOE_GRP definition
CREATE TABLE "TP_TASK_IOE_GRP"
   (	"TASK_NO" VARCHAR2(100) NOT NULL ENABLE,
	"IOE_GRP_CD" VARCHAR2(3) NOT NULL ENABLE,
	 CONSTRAINT "PK_TP_TASK_IOE_GRP" PRIMARY KEY ("TASK_NO", "IOE_GRP_CD")
	 );

COMMENT ON COLUMN TP_TASK_IOE_GRP.TASK_NO IS '과제번호';
COMMENT ON COLUMN TP_TASK_IOE_GRP.IOE_GRP_CD IS '비목 그룹 코드';

-- TP_TAX_INV definition
CREATE TABLE "TP_TAX_INV"
   (	"ISSUE_ID" VARCHAR2(24) NOT NULL ENABLE,
	"ASP_ORG_CD" VARCHAR2(4),
	"ASP_ID" VARCHAR2(24),
	"ASP_REF_DOC_ID" VARCHAR2(24),
	"ASP_IS_D" VARCHAR2(14),
	"IS_D" VARCHAR2(8),
	"TYPE_CD" VARCHAR2(4),
	"PRPS_CD" VARCHAR2(2),
	"MDF_RSN" VARCHAR2(2),
	"RMK" VARCHAR2(500),
	"IM_DOC_ID" VARCHAR2(15),
	"IM_ACP_ST_D" VARCHAR2(8),
	"IM_ACP_END_D" VARCHAR2(8),
	"IM_ITM_QTY" NUMBER(6,0),
	"SND_BSN_RG_N" VARCHAR2(13),
	"SND_TX_ID" VARCHAR2(4),
	"SND_NAME" VARCHAR2(140),
	"SND_RPRSND_NM" VARCHAR2(60),
	"SND_ADR" VARCHAR2(300),
	"SND_BCND" VARCHAR2(80),
	"SND_ITP" VARCHAR2(200),
	"SND_CHP_DPT" VARCHAR2(80),
	"SND_CHP_NM" VARCHAR2(60),
	"SND_CHP_PHN" VARCHAR2(20),
	"SND_CHP_EM" VARCHAR2(40),
	"RCV_BSN_CD" VARCHAR2(2),
	"RCV_BSN_RG_N" VARCHAR2(13),
	"RCV_TX_ID" VARCHAR2(4),
	"RCV_NAME" VARCHAR2(140),
	"RCV_RPRS_NM" VARCHAR2(60),
	"RCV_ADR" VARCHAR2(300),
	"RCV_BCND" VARCHAR2(120),
	"RCV_ITP" VARCHAR2(200),
	"RCV_CHP_DPT" VARCHAR2(80),
	"RCV_CHP_NM" VARCHAR2(60),
	"RCV_CHP_PHN" VARCHAR2(40),
	"RCV_CHP_EM" VARCHAR2(40),
	"RCV_SUB_CHP_DPT" VARCHAR2(80),
	"RCV_SUB_CHP_NM" VARCHAR2(60),
	"RCV_SUB_CHP_PHN" VARCHAR2(20),
	"RCV_SUB_CHP_EM" VARCHAR2(40),
	"BRK_BSN_RG_N" VARCHAR2(13),
	"BRK_TX_ID" VARCHAR2(4),
	"BRK_NAME" VARCHAR2(140),
	"BRK_RPRS_NM" VARCHAR2(60),
	"BRK_ADR" VARCHAR2(300),
	"BRK_BCND" VARCHAR2(80),
	"BRK_ITP" VARCHAR2(200),
	"BRK_CHP_DPT" VARCHAR2(80),
	"BRK_CHP_NM" VARCHAR2(60),
	"BRK_CHP_PHN" VARCHAR2(20),
	"BRK_CHP_EM" VARCHAR2(40),
	"CS_AMT" NUMBER(18,0),
	"CHK_AMT" NUMBER(18,0),
	"BIL_AMT" NUMBER(18,0),
	"CRDT_AMT" NUMBER(18,0),
	"SUPPLY_AMT" NUMBER(18,0),
	"TAX_AMT" NUMBER(18,0),
	"TOT_AMT" NUMBER(18,0),
	"SHC_ETC_INFO" VARCHAR2(1000),
	"EXE_RG_AMT" NUMBER(18,0),
	"RSN_RMK" VARCHAR2(300),
	 CONSTRAINT "PK_TP_TP_TAX_INV" PRIMARY KEY ("ISSUE_ID")
	 );

COMMENT ON COLUMN TP_TAX_INV.ISSUE_ID IS '세금계산서 승인번호 (Primary Key)';
COMMENT ON COLUMN TP_TAX_INV.ASP_ORG_CD IS 'ASP 업체코드';
COMMENT ON COLUMN TP_TAX_INV.ASP_ID IS '서비스 사업자 관리번호';
COMMENT ON COLUMN TP_TAX_INV.ASP_REF_DOC_ID IS '사업자 관리 번호';
COMMENT ON COLUMN TP_TAX_INV.ASP_IS_D IS '전자세금계산서 발행일시';
COMMENT ON COLUMN TP_TAX_INV.IS_D IS '전자세금계산서 작성일자';
COMMENT ON COLUMN TP_TAX_INV.TYPE_CD IS '전자세금계산서 종류';
COMMENT ON COLUMN TP_TAX_INV.PRPS_CD IS '영수/청구 구분자';
COMMENT ON COLUMN TP_TAX_INV.MDF_RSN IS '수정 사유 코드';
COMMENT ON COLUMN TP_TAX_INV.RMK IS '비고';
COMMENT ON COLUMN TP_TAX_INV.IM_DOC_ID IS '수입 신고서 번호';
COMMENT ON COLUMN TP_TAX_INV.IM_ACP_ST_D IS '일괄발급 시작일자';
COMMENT ON COLUMN TP_TAX_INV.IM_ACP_END_D IS '일괄발급 종료일자';
COMMENT ON COLUMN TP_TAX_INV.IM_ITM_QTY IS '일괄발급 수입 총건';
COMMENT ON COLUMN TP_TAX_INV.SND_BSN_RG_N IS '공급자 사업자등록번호';
COMMENT ON COLUMN TP_TAX_INV.SND_TX_ID IS '공급자 종사업장 식별코드';
COMMENT ON COLUMN TP_TAX_INV.SND_NAME IS '공급업체 사업체명';
COMMENT ON COLUMN TP_TAX_INV.SND_RPRSND_NM IS '공급업체 대표자명';
COMMENT ON COLUMN TP_TAX_INV.SND_ADR IS '공급업체 주소';
COMMENT ON COLUMN TP_TAX_INV.SND_BCND IS '공급업체 업태';
COMMENT ON COLUMN TP_TAX_INV.SND_ITP IS '공급업체 업종';
COMMENT ON COLUMN TP_TAX_INV.SND_CHP_DPT IS '공급업체 담당부서';
COMMENT ON COLUMN TP_TAX_INV.SND_CHP_NM IS '공급업체 담당자명';
COMMENT ON COLUMN TP_TAX_INV.SND_CHP_PHN IS '공급업체 담당자 전화번호';
COMMENT ON COLUMN TP_TAX_INV.SND_CHP_EM IS '공급업체 담당자 이메일';
COMMENT ON COLUMN TP_TAX_INV.RCV_BSN_CD IS '수신업체 사업자등록번호 구분코드';
COMMENT ON COLUMN TP_TAX_INV.RCV_BSN_RG_N IS '수신업체 사업자등록번호';
COMMENT ON COLUMN TP_TAX_INV.RCV_TX_ID IS '수신업체 종사업장 식별코드';
COMMENT ON COLUMN TP_TAX_INV.RCV_NAME IS '수신업체 사업체명';
COMMENT ON COLUMN TP_TAX_INV.RCV_RPRS_NM IS '수신업체 대표자명';
COMMENT ON COLUMN TP_TAX_INV.RCV_ADR IS '수신업체 주소';
COMMENT ON COLUMN TP_TAX_INV.RCV_BCND IS '수신업체 업태';
COMMENT ON COLUMN TP_TAX_INV.RCV_ITP IS '수신업체 업종';
COMMENT ON COLUMN TP_TAX_INV.RCV_CHP_DPT IS '수신업체 담당부서';
COMMENT ON COLUMN TP_TAX_INV.RCV_CHP_NM IS '수신업체 담당자명';
COMMENT ON COLUMN TP_TAX_INV.RCV_CHP_PHN IS '수신업체 담당자 전화번호';
COMMENT ON COLUMN TP_TAX_INV.RCV_CHP_EM IS '수신업체 담당자 이메일';
COMMENT ON COLUMN TP_TAX_INV.RCV_SUB_CHP_DPT IS '수신업체 부서 담당부서';
COMMENT ON COLUMN TP_TAX_INV.RCV_SUB_CHP_NM IS '수신업체 부서 담당자명';
COMMENT ON COLUMN TP_TAX_INV.RCV_SUB_CHP_PHN IS '수신업체 부서 담당자 전화번호';
COMMENT ON COLUMN TP_TAX_INV.RCV_SUB_CHP_EM IS '수신업체 부서 담당자 이메일';
COMMENT ON COLUMN TP_TAX_INV.BRK_BSN_RG_N IS '수탁사업자 사업자등록번호';
COMMENT ON COLUMN TP_TAX_INV.BRK_TX_ID IS '수탁사업자 종사업장 식별코드';
COMMENT ON COLUMN TP_TAX_INV.BRK_NAME IS '수탁사업자 사업체명';
COMMENT ON COLUMN TP_TAX_INV.BRK_RPRS_NM IS '수탁사업자 대표자명';
COMMENT ON COLUMN TP_TAX_INV.BRK_ADR IS '수탁사업자 주소';
COMMENT ON COLUMN TP_TAX_INV.BRK_BCND IS '수탁사업자 업태';
COMMENT ON COLUMN TP_TAX_INV.BRK_ITP IS '수탁사업자 업종';
COMMENT ON COLUMN TP_TAX_INV.BRK_CHP_DPT IS '수탁사업자 담당부서';
COMMENT ON COLUMN TP_TAX_INV.BRK_CHP_NM IS '수탁사업자 담당자명';
COMMENT ON COLUMN TP_TAX_INV.BRK_CHP_PHN IS '수탁사업자 담당자 전화번호';
COMMENT ON COLUMN TP_TAX_INV.BRK_CHP_EM IS '수탁사업자 담당자 이메일';
COMMENT ON COLUMN TP_TAX_INV.CS_AMT IS '현금 금액';
COMMENT ON COLUMN TP_TAX_INV.CHK_AMT IS '수표 금액';
COMMENT ON COLUMN TP_TAX_INV.BIL_AMT IS '어음 금액';
COMMENT ON COLUMN TP_TAX_INV.CRDT_AMT IS '외상 금액';
COMMENT ON COLUMN TP_TAX_INV.SUPPLY_AMT IS '총 공급가액';
COMMENT ON COLUMN TP_TAX_INV.TAX_AMT IS '총 세액';
COMMENT ON COLUMN TP_TAX_INV.TOT_AMT IS '총액 (공급가액 + 세액)';
COMMENT ON COLUMN TP_TAX_INV.SHC_ETC_INFO IS '기타 정보';
COMMENT ON COLUMN TP_TAX_INV.EXE_RG_AMT IS '이행액';
COMMENT ON COLUMN TP_TAX_INV.RSN_RMK IS '비고';

-- TP_TAX_INV_ITM definition
CREATE TABLE "TP_TAX_INV_ITM"
   (	"ISSUE_ID" VARCHAR2(24) NOT NULL ENABLE,
	"ITM_SEQ_N" NUMBER(2,0) NOT NULL ENABLE,
	"SPL_D" VARCHAR2(8),
	"NM" VARCHAR2(1200),
	"INFO_TXT" VARCHAR2(90),
	"ITM_DESC" VARCHAR2(4000),
	"QTY" NUMBER(12,0),
	"UPRC" NUMBER(18,0),
	"SUPPLY_AMT" NUMBER(18,0),
	"TAX_AMT" NUMBER(18,0),
	 CONSTRAINT "PK_TP_TAX_INV_ITM" PRIMARY KEY ("ISSUE_ID", "ITM_SEQ_N")
	 );

COMMENT ON COLUMN TP_TAX_INV_ITM.ISSUE_ID IS '세금계산서 승인번호';
COMMENT ON COLUMN TP_TAX_INV_ITM.ITM_SEQ_N IS '물품 일련번호';
COMMENT ON COLUMN TP_TAX_INV_ITM.SPL_D IS '물품 공급일자';
COMMENT ON COLUMN TP_TAX_INV_ITM.NM IS '물품명';
COMMENT ON COLUMN TP_TAX_INV_ITM.INFO_TXT IS '물품에 대한 규격';
COMMENT ON COLUMN TP_TAX_INV_ITM.ITM_DESC IS '물품과 관련된 자유기술문';
COMMENT ON COLUMN TP_TAX_INV_ITM.QTY IS '물품 수량';
COMMENT ON COLUMN TP_TAX_INV_ITM.UPRC IS '물품 단가';
COMMENT ON COLUMN TP_TAX_INV_ITM.SUPPLY_AMT IS '물품 공급 가액';
COMMENT ON COLUMN TP_TAX_INV_ITM.TAX_AMT IS '물품 세액';